import '../framework/framework.dart';
import 'package:collection/collection.dart';

/// Base class for all render tree mutations generated by reconciliation.
sealed class RenderMutation {
  final List<int> path;
  const RenderMutation(this.path);
}

/// Indicates inserting a new component at [path].
final class InsertMutation extends RenderMutation {
  final Component component;
  const InsertMutation(super.path, this.component);

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InsertMutation &&
          const ListEquality().equals(other.path, path) &&
          other.component == component;

  @override
  int get hashCode => Object.hash(const ListEquality().hash(path), component);

  @override
  String toString() => 'InsertMutation(path: $path, component: $component)';
}

/// Indicates updating an existing component at [path].
final class UpdateMutation extends RenderMutation {
  final Component oldComponent;
  final Component newComponent;
  final Map<String, String>? attributeChanges;

  const UpdateMutation({
    required List<int> path,
    required this.oldComponent,
    required this.newComponent,
    this.attributeChanges,
  }) : super(path);

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UpdateMutation &&
          const ListEquality().equals(other.path, path) &&
          other.oldComponent == oldComponent &&
          other.newComponent == newComponent &&
          const MapEquality().equals(other.attributeChanges, attributeChanges);

  @override
  int get hashCode => Object.hash(
        const ListEquality().hash(path),
        oldComponent,
        newComponent,
        const MapEquality().hash(attributeChanges),
      );

  @override
  String toString() =>
      'UpdateMutation(path: $path, old: $oldComponent, new: $newComponent, attributeChanges: $attributeChanges)';
}

/// Indicates deleting a component at [path].
final class DeleteMutation extends RenderMutation {
  final Component component;
  const DeleteMutation(super.path, this.component);

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeleteMutation &&
          const ListEquality().equals(other.path, path) &&
          other.component == component;

  @override
  int get hashCode => Object.hash(const ListEquality().hash(path), component);

  @override
  String toString() => 'DeleteMutation(path: $path, component: $component)';
}

/// Indicates moving a component from [fromPath] to [toPath].
final class MoveMutation extends RenderMutation {
  final List<int> fromPath;
  final List<int> toPath;
  final Component component;

  const MoveMutation({
    required this.fromPath,
    required this.toPath,
    required this.component,
  }) : super(toPath);

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MoveMutation &&
          const ListEquality().equals(other.fromPath, fromPath) &&
          const ListEquality().equals(other.toPath, toPath) &&
          other.component == component;

  @override
  int get hashCode => Object.hash(
        const ListEquality().hash(fromPath),
        const ListEquality().hash(toPath),
        component,
      );

  @override
  String toString() =>
      'MoveMutation(fromPath: $fromPath, toPath: $toPath, component: $component)';
}
